# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb

# Cells
A notebook is a list of cells. Cells contain either explanatory text or executable code and its output. Click a cell to select it.

## Code cells
Below is a **code cell**. Once the toolbar button indicates CONNECTED, click in the cell to select it and execute the contents in the following ways:

* Click the **Play icon** in the left gutter of the cell;
* Type **Cmd/Ctrl+Enter** to run the cell in place;
* Type **Shift+Enter** to run the cell and move focus to the next cell (adding one if none exists); or
* Type **Alt+Enter** to run the cell and insert a new code cell immediately below it.

There are additional options for running some or all cells in the **Runtime** menu.
"""

a = 10
a

"""## Text cells
This is a **text cell**. You can **double-click** to edit this cell. Text cells
use markdown syntax. To learn more, see our [markdown
guide](/notebooks/markdown_guide.ipynb).

You can also add math to text cells using [LaTeX](http://www.latex-project.org/)
to be rendered by [MathJax](https://www.mathjax.org). Just place the statement
within a pair of **\$** signs. For example `$\sqrt{3x-1}+(1+x)^2$` becomes
$\sqrt{3x-1}+(1+x)^2.$

# New Section

## Adding and moving cells
You can add new cells by using the **+ CODE** and **+ TEXT** buttons that show when you hover between cells. These buttons are also in the toolbar above the notebook where they can be used to add a cell below the currently selected cell.

You can move a cell by selecting it and clicking **Cell Up** or **Cell Down** in the top toolbar. 

Consecutive cells can be selected by "lasso selection" by dragging from outside one cell and through the group.  Non-adjacent cells can be selected concurrently by clicking one and then holding down Ctrl while clicking another.  Similarly, using Shift instead of Ctrl will select all intermediate cells.

# Working with python
Colaboratory is built on top of [Jupyter Notebook](https://jupyter.org/). Below are some examples of convenience functions provided.

Long running python processes can be interrupted. Run the following cell and select **Runtime -> Interrupt execution** (*hotkey: Cmd/Ctrl-M I*) to stop execution.
"""

import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")

"""## System aliases

Jupyter includes shortcuts for common operations, such as ls:
"""

!ls /bin

"""That `!ls` probably generated a large output. You can select the cell and clear the output by either: 

1. Clicking on the clear output button (x) in the toolbar above the cell; or
2. Right clicking the left gutter of the output area and selecting "Clear output" from the context menu.

Execute any other process using `!` with string interpolation from python variables, and note the result can be assigned to a variable:
"""

message = 'Colaboratory is great!'
foo = !echo -e '$message\n$message'
foo

"""## Magics
Colaboratory shares the notion of magics from Jupyter. There are shorthand annotations that change how a cell's text is executed. To learn more, see [Jupyter's magics page](http://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Cell%20Magics.ipynb). 

"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <marquee style='width: 30%; color: blue;'><b>Whee!</b></marquee>

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 450 400" width="200" height="200">
#   <rect x="80" y="60" width="250" height="250" rx="20" style="fill:red; stroke:black; fill-opacity:0.7" />
#   <rect x="180" y="110" width="250" height="250" rx="40" style="fill:blue; stroke:black; fill-opacity:0.5;" />
# </svg>

"""## Automatic completions and exploring code

Colab provides automatic completions to explore attributes of Python objects, as well as to quickly view documentation strings. As an example, first run the following cell to import the  [`numpy`](http://www.numpy.org) module.
"""

import numpy as np

"""If you now insert your cursor after `np` and press **Period**(`.`), you will see the list of available completions within the `np` module. Completions can be opened again by using **Ctrl+Space**."""

np

"""If you type an open parenthesis after any function or class in the module, you will see a pop-up of its documentation string:"""

np.ndarray

"""The documentation can be opened again using **Ctrl+Shift+Space** or you can view the documentation for method by mouse hovering over the method name.

When hovering over the method name the `Open in tab` link will open the documentation in a persistent pane. The `View source` link will navigate to the source code for the method.

## Exception Formatting

Exceptions are formatted nicely in Colab outputs:
"""

x = 1
y = 4
z = y/(1-x)

"""## Rich, interactive outputs
Until now all of the generated outputs have been text, but they can be more interesting, like the chart below. 
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Fills and Alpha Example")
plt.show()

"""# Integration with Drive

Colaboratory is integrated with Google Drive. It allows you to share, comment, and collaborate on the same document with multiple people:

* The **SHARE** button (top-right of the toolbar) allows you to share the notebook and control permissions set on it.

* **File->Make a Copy** creates a copy of the notebook in Drive.

* **File->Save** saves the File to Drive. **File->Save and checkpoint** pins the version so it doesn't get deleted from the revision history. 

* **File->Revision history** shows the notebook's revision history.

## Commenting on a cell
You can comment on a Colaboratory notebook like you would on a Google Document. Comments are attached to cells, and are displayed next to the cell they refer to. If you have **comment-only** permissions, you will see a comment button on the top right of the cell when you hover over it.

If you have edit or comment permissions you can comment on a cell in one of three ways: 

1. Select a cell and click the comment button in the toolbar above the top-right corner of the cell.
1. Right click a text cell and select **Add a comment** from the context menu.
3. Use the shortcut **Ctrl+Shift+M** to add a comment to the currently selected cell. 

You can resolve and reply to comments, and you can target comments to specific collaborators by typing *+[email address]* (e.g., `+user@domain.com`). Addressed collaborators will be emailed. 

The Comment button in the top-right corner of the page shows all comments attached to the notebook.
"""

heroes = ['Batman', 'Superman', 'Spiderman']
print(heroes)
heroes.index('Batman')
print(heroes[0])
heroes.append('Wonderwoman')
heroes.remove('Batman')
print(heroes[2])
heroes.index('Superman')
print(heroes)

heroes = ['Batman', 'Superman', 'Spiderman']
print('Batman' in heroes)
print('Ironman' not in heroes)
hero = 'Superman'
print(hero in heroes)
print('Ironman' not in ['Captain America', 'Ironman', 'Hulk'])

heroes1 = ['Batman', 'Superman', 'Spiderman']
heroes2 = ['Captain America', 'Ironman', 'Hulk']
print(heroes1 + heroes2)
heroes = heroes1 + heroes2
heroes2.remove('Hulk')
print(heroes2)

heroes = ['Batman', 'Superman', 'spiderman', 'Captain America', 'Ironman', 'Hulk']
heroes.sort()
print(heroes)

heroes = ['Batman', 'Superman', 'spiderman', 'Captain America', 'Ironman', 'Hulk']
print(sorted(heroes))
print(list(reversed(heroes)))
print(heroes)

heroes = ['Batman', 'Superman', 'spiderman', 'Captain America', 'Ironman', 'Hulk']
for hero in heroes:
  print ("my hero is {}".format(hero))

numbers = [1, 2, 3, 4, 5, 6]
total = 0
for number in numbers:
  total = total + number
print(total)

numbers = [1, 2, 3, 4, 5, 6]
total = sum(numbers)
print(total)

age = input("Type your age: ")
age = int(age)
if age >= 100:
    print("That is not a valid age")
elif age >= 18:
    print("You are old enough to drive")
elif age <= 0:
    print("That is not a valid age")
else:
    print("You are not old enough to drive")

age = input("Type your age: ")
age = int(age)
if age >= 100 or age <= 0:
        print("That is not a valid age")
elif age >= 18:
        print("You are old enough to drive")
else:
        print("You are not old enough to drive")

numbers = [200, 100, 43, 10, -10, 0]
for number in numbers:
    if number > 100:
        print(f"{number} is greater than 100")

numbers = [200, 100, 43, 10, -10, 0]
filtered = []

for number in numbers:
    if number > 30:
        filtered.append(number)
print(filtered)

numbers = [1, 2, 3, 4, 5, 6]

for number in numbers:
    if (number%2) == 0:
        print(f"{number} is even")
    else:
        print(f"{number} is odd")

numbers = [1, 2, 3, 4, 5, 6]
evens = [ ]
odds = [ ]

for number in numbers:
    if (number%2) == 0:
        evens.append(number)

for number in numbers:
    if (number%2) != 0:
        odds.append(number)

print(evens)
print(odds)

numbers = [1, 2, 3, 4, 5, 6]
doubles = [ ]

for number in numbers:
    number *= 2
    doubles.append(number)
    
print(doubles)

numbers = [1, 2, 3, 4, 5, 6]

evens = [number for number in numbers if (number % 2) == 0]
odds = [number for number in numbers if (number % 2) != 0]

print(evens)
print(odds)

numbers = [1, 2, 3, 4, 5, 6]
doubles = [number * 2 for number in numbers]
print(doubles)

name_lengths = []
names = ["alice", "bob", "carol"]
name_lengths = [len(name) for name in names]

print(name_lengths)

record = ["alice", 5]

name, length = record

print(f"{name} have a length of {length}")

records = [ ["alice", 5], ["bob", 3], ["carol", 5],
]
for name, length in records:
    print(f"{name} have a length of {length}")

names = ["alice", "bob", "carol"]
name_lengths = [5, 3, 5]

for name, length in zip(names, name_lengths):
    print(f"{name} have a length of {length}")
    
print (zip(names, name_lengths))
print (list(zip(names, name_lengths)))

names = ["alice", "bob", "carol", "marvin"]
name_lengths = [5, 3, 5]
genders = ["female", "male", "female"]
ages = [15, 22, 34]
filtered = []

for name, length, gender, age in zip(names, name_lengths, genders, ages):
    print(f"{name} have a length of {length}. They are {gender}. Ages are {age}")